# Generated by Django 6.0.7 on 2026-08-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_custom_data_transactioncolumn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('FEE', 'Student Fee'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('SALARY', 'Salary'), ('LOAN', 'Loan'), ('BANK', 'Bank')], max_length=20),
        ),
    ]
