# Generated by Django 6.0.7 on 2026-08-22 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATE_STUDENT', 'Create Student'), ('UPDATE_STUDENT', 'Update Student'), ('DELETE_STUDENT', 'Delete Student'), ('VERIFY_STUDENT', 'Verify Student'), ('REJECT_STUDENT', 'Reject Student'), ('REOPEN_STUDENT', 'Reopen Student'), ('CREATE_EVENT', 'Create Event'), ('UPDATE_EVENT', 'Update Event'), ('DELETE_EVENT', 'Delete Event'), ('SUBMIT_EVENT', 'Submit Event'), ('APPROVE_EVENT', 'Approve Event'), ('REJECT_EVENT', 'Reject Event'), ('CREATE_EXPENSE', 'Create Expense'), ('UPDATE_EXPENSE', 'Update Expense'), ('DELETE_EXPENSE', 'Delete Expense'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('actor_role', models.CharField(help_text='Store the role at time of action', max_length=20)),
                ('target_model', models.CharField(help_text="Model name that was affected (e.g., 'Student', 'Event')", max_length=100)),
                ('target_id', models.UUIDField(blank=True, help_text='ID of the affected object', null=True)),
                ('target_description', models.CharField(blank=True, help_text='Human-readable description of affected object', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context about the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='activity_ac_timesta_b82f2c_idx'), models.Index(fields=['actor'], name='activity_ac_actor_i_29e3da_idx'), models.Index(fields=['action_type'], name='activity_ac_action__20d4e8_idx')],
            },
        ),
    ]
