# Generated by Django 6.0.7 on 2026-08-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('CREATE_STUDENT', 'Create Student'), ('UPDATE_STUDENT', 'Update Student'), ('DELETE_STUDENT', 'Delete Student'), ('VERIFY_STUDENT', 'Verify Student'), ('REJECT_STUDENT', 'Reject Student'), ('REOPEN_STUDENT', 'Reopen Student'), ('CREATE_EVENT', 'Create Event'), ('UPDATE_EVENT', 'Update Event'), ('DELETE_EVENT', 'Delete Event'), ('SUBMIT_EVENT', 'Submit Event'), ('APPROVE_EVENT', 'Approve Event'), ('REJECT_EVENT', 'Reject Event'), ('CREATE_EXPENSE', 'Create Expense'), ('UPDATE_EXPENSE', 'Update Expense'), ('DELETE_EXPENSE', 'Delete Expense'), ('CREATE_TRANSACTION', 'Create Transaction'), ('UPDATE_TRANSACTION', 'Update Transaction'), ('DELETE_TRANSACTION', 'Delete Transaction'), ('APPROVE_TRANSACTION', 'Approve Transaction'), ('REJECT_TRANSACTION', 'Reject Transaction'), ('CREATE_TRANSACTION_CATEGORY', 'Create Transaction Category'), ('DELETE_TRANSACTION_CATEGORY', 'Delete Transaction Category'), ('CREATE_TRANSACTION_COLUMN', 'Create Transaction Column'), ('DELETE_TRANSACTION_COLUMN', 'Delete Transaction Column'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
