# Generated by Django 6.0.7 on 2026-08-04 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicsession'),
        ('students', '0002_feecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.section'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.schoolclass'),
        ),
    ]
