# Generated by Django 6.0.7 on 2026-08-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_populate_student_academics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
    ]
