# Generated by Django 6.0.7 on 2026-08-17 19:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_age_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
