# Generated by Django 6.0.7 on 2026-08-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='additional_fees',
            field=models.JSONField(blank=True, default=dict, help_text="Flexible additional fees (e.g., {'lab_fee': 500, 'sports_fee': 200})"),
        ),
        migrations.AddField(
            model_name='student',
            name='annual_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Annual fee amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='cab_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Transport/Cab fee amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_due_day',
            field=models.PositiveIntegerField(default=10, help_text='Day of month when fee is due (e.g., 10 for 10th of every month)'),
        ),
        migrations.AddField(
            model_name='student',
            name='late_fee_per_day',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Late fee charged per day after due date', max_digits=8),
        ),
        migrations.AddField(
            model_name='student',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly fee amount', max_digits=10),
        ),
    ]
