# Generated by Django 6.0.7 on 2026-08-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_additional_fees_student_annual_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='UNPAID', help_text='Payment status', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='last_payment_date',
            field=models.DateField(blank=True, help_text='Date of last payment', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='next_payment_due',
            field=models.DateField(blank=True, help_text='Next payment due date', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total_fee_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total fee amount due (calculated automatically)', max_digits=12),
        ),
        migrations.AddField(
            model_name='student',
            name='total_fee_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total fee amount paid', max_digits=12),
        ),
    ]
