# Generated by Django 6.0.7 on 2026-08-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_fee_status_student_last_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='annual_fee_paid',
            field=models.BooleanField(default=False, help_text='Whether annual fee has been paid for current year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_fee_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total fee amount paid (excluding annual fee)', max_digits=12),
        ),
    ]
