# Generated by Django 6.0.7 on 2026-08-22 11:06

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_fee_structure_due_late_fee'),
        ('students', '0011_student_additional_fees_student_annual_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('MONTHLY', 'Monthly Fee'), ('ANNUAL', 'Annual Fee'), ('CAB', 'Cab Fee'), ('ADDITIONAL', 'Additional Fee'), ('OTHER', 'Other')], default='MONTHLY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('receipt', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('receipt_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('additional_fee_name', models.CharField(blank=True, help_text='Name of additional fee if payment_type is ADDITIONAL', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_payments', to='students.student')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
