# Generated by Django 6.0.7 on 2026-08-23 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_simplepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplepayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
