# Generated by Django 6.0.7 on 2026-08-26 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_monthly_fee_ledger'),
        ('students', '0013_student_annual_fee_paid_alter_student_total_fee_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Day Scholar', 'Hostel/Boarding'", max_length=100)),
                ('boarding_type', models.CharField(choices=[('day_scholar', 'Day Scholar'), ('hostel', 'Hostel/Boarding')], default='day_scholar', max_length=20)),
                ('applicable_class_range', models.CharField(help_text="e.g., 'Pre-Nursery', 'Nursery & KG', 'I-V', 'VI-VII', 'VI-VIII'", max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['session', 'boarding_type', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_label', models.CharField(help_text="e.g., '2022-2023', '2026-2027'", max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='The active session is used for new admissions and fee collections')),
                ('start_date', models.DateField(blank=True, help_text='Session start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Session end date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', '-session_label'],
            },
        ),
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g., 'Registration Fees', 'Tuition Fees', 'Hostel/Accommodation'", max_length=200)),
                ('frequency', models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for the frequency (not annual equivalent)', max_digits=10)),
                ('annual_equivalent', models.DecimalField(decimal_places=2, default=0, help_text='Auto-computed: monthly*12 or yearly amount or one_time amount', max_digits=12)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this fee head is mandatory for all students')),
                ('display_order', models.IntegerField(default=0)),
                ('editable_by', models.CharField(choices=[('admin', 'Admin Only'), ('admin_operator', 'Admin + Operator')], default='admin_operator', help_text='Who can edit this fee head', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this fee head')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive heads won't be applied to new assignments")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_heads', to='fees.feecategorygroup')),
            ],
            options={
                'ordering': ['group', 'display_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='feecategorygroup',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_category_groups', to='fees.feesession'),
        ),
        migrations.AlterUniqueTogether(
            name='feecategorygroup',
            unique_together={('session', 'name', 'boarding_type')},
        ),
        migrations.CreateModel(
            name='ClassFeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text="e.g., 'Nursery', 'KG', 'I', 'II', ... 'VIII'", max_length=50)),
                ('default_uniform_gender_required', models.BooleanField(default=True, help_text='Whether uniform selection applies to this class')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_scholar_group', models.ForeignKey(blank=True, help_text='Fee group for day scholar students in this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_scholar_classes', to='fees.feecategorygroup')),
                ('hostel_group', models.ForeignKey(blank=True, help_text='Fee group for hostel students in this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_classes', to='fees.feecategorygroup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_mappings', to='fees.feesession')),
            ],
            options={
                'ordering': ['session', 'class_name'],
                'unique_together': {('session', 'class_name')},
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_type', models.CharField(choices=[('day_scholar', 'Day Scholar'), ('hostel', 'Hostel/Boarding')], default='day_scholar', max_length=20)),
                ('fee_heads', models.JSONField(default=list, help_text='JSON array of fee heads copied from FeeHead at assignment time')),
                ('uniform_selection', models.JSONField(blank=True, default=dict, help_text='JSON: {gender, items: [{name, price, selected}]}')),
                ('transportation_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Transportation fee if applicable', max_digits=10, null=True)),
                ('created_from_template', models.BooleanField(default=True, help_text='Whether this was created from a fee structure template')),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_fee_assignments', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to='fees.feesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='students.student')),
            ],
            options={
                'ordering': ['-session__start_date', 'student'],
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.CreateModel(
            name='UniformFeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls')], max_length=10)),
                ('item_name', models.CharField(help_text="e.g., 'Full Shirt', 'Tunic', 'Socks 2 Set', 'Tie', 'Belt'", max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uniform_items', to='fees.feesession')),
            ],
            options={
                'ordering': ['session', 'gender', 'display_order', 'item_name'],
                'unique_together': {('session', 'gender', 'item_name')},
            },
        ),
    ]
